# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Publish Node.js Package

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'luckyphoenix version, eg: 1.0.1'
        required: true
        default: ''
        type: string
permissions:
  id-token: write
jobs:
  publish:
    runs-on: ubuntu-latest
    if: github.event.inputs.version != ''
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/
      - name: Publish ${{ env.PACKAGE }}@${{ github.event.inputs.version }}
        run: |
          git config --global user.email "${{ secrets.GIT_EMAIL }}"
          git config --global user.name "${{ github.repository_owner }}"
          # '[0-9]*.[0-9]*.[0-9]*'
          version=$(npm version ${VERSION} | sed "s/v//g" || echo -n 1.0.1)
          if ! echo "$(npm show ${PACKAGE} versions)" | grep -q "${version//v/}"; then npm publish --provenance --access public 2>&1 || echo -e "\e[31m ${PACKAGE}@${version} publish failed \e[0m"; else echo -e "\e[33m ${PACKAGE}@${VERSION} exists \e[0m"; fi
        env:
          PACKAGE: 'luckyphoenix'
          VERSION: ${{ github.event.inputs.version }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
